<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#数据处理" data-toc-modified-id="数据处理-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>数据处理</a></span><ul class="toc-item"><li><span><a href="#导入数据" data-toc-modified-id="导入数据-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>导入数据</a></span></li><li><span><a href="#分析" data-toc-modified-id="分析-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>分析</a></span></li><li><span><a href="#iAMEND,iRESTATEMENT,iTYPE" data-toc-modified-id="iAMEND,iRESTATEMENT,iTYPE-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>iAMEND,iRESTATEMENT,iTYPE</a></span><ul class="toc-item"><li><span><a href="#amend" data-toc-modified-id="amend-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>amend</a></span></li><li><span><a href="#Restatement" data-toc-modified-id="Restatement-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Restatement</a></span></li><li><span><a href="#type" data-toc-modified-id="type-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>type</a></span></li></ul></li></ul></li><li><span><a href="#单独分析一支基金" data-toc-modified-id="单独分析一支基金-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>单独分析一支基金</a></span><ul class="toc-item"><li><span><a href="#fund1" data-toc-modified-id="fund1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>fund1</a></span></li><li><span><a href="#fund2" data-toc-modified-id="fund2-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>fund2</a></span></li><li><span><a href="#fund3" data-toc-modified-id="fund3-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>fund3</a></span></li></ul></li><li><span><a href="#old" data-toc-modified-id="old-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>old</a></span></li></ul></div>

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
mpl.rcParams['axes.unicode_minus']=False #用来正常显示负号
import seaborn as sns
import numpy as np
import pandas as pd
from itertools import combinations,combinations_with_replacement
from collections import OrderedDict

import os,time,datetime,sys

import requests
import os
from lxml import etree
from urllib import parse
import urllib


from IPython.core.display import display, HTML

pd.set_option('display.max_rows',None)

In [29]:
data_13f.iFILING_DATE.unique()
len(data_13f.iFILING_DATE.unique())

array(['2000/1/3', '2000/1/11', '2000/1/12', '2000/1/18', '2000/1/24',
       '2000/1/26', '2000/1/31', '2000/2/2', '2000/2/3', '2000/2/7',
       '2000/2/9', '2000/2/10', '2000/2/11', '2000/2/14', '2000/2/15'],
      dtype=object)

15

In [30]:
data_13f.iPERIOD_END.unique()
len(data_13f.iPERIOD_END.unique())

array(['1999/9/30', '1999/12/31'], dtype=object)

2

In [14]:
data_price = pd.read_csv("D:/news/i_Metrix_prices_sample.csv")

In [15]:
data_price.shape

(10000, 9)

In [31]:
data_price.pSP_DATE.unique()
len(data_price.pSP_DATE.unique())

array(['1996/1/2', '1996/1/3', '1996/1/4', ..., '2014/2/14', '2009/5/20',
       '2007/8/24'], dtype=object)

2779

## 数据处理

按照标准找出survival funds

### 导入数据

In [28]:
Sce = pd.read_csv("D:/news/13f_filings_fractions_new.csv")

In [30]:
Sce.shape

(57569236, 11)

### 分析

In [4]:
Sce.shape

(57569236, 11)

In [ ]:
# iCIK(char)---identifier for each company's fund 
# iCUSIP(char)---identifier for each security
# iPERIOD_END(date)---period end
# iFILING_DATE(date)---actual filing date
# iQTY(int)---number of shares
# iMARKET_VALUE(float)---total amount of money invested

problem 1：
iAMEND(修改) --- [0,1]  this variable can be used to choose suitable funds
iRESTATEMENT(重申，再次声明) --- [0,1]
iTYPE --- [0,1,2,3,4,5] --- what types/classifications

problem 2:
??? iLONG_FRACTION --- Is this the total amount of money invested on istock 
                   divided by the the whole mkt value of the stock?
                  Or it's the proportion compared to the whole fund?

In [20]:
Sce.head(1000)

iRECORD_ID     iCIK     iCUSIP iPERIOD_END iFILING_DATE  iAMEND  \
0       4443748   216235  055622104  1999-09-30   2000-01-03       0   
1       4443749   216235  020039103  1999-09-30   2000-01-03       0   
2       4443750   216235  713448108  1999-09-30   2000-01-03       0   
3       4443751   216235  002824100  1999-09-30   2000-01-03       0   
4       4443752   216235  05964H105  1999-09-30   2000-01-03       0   
5       4443753   216235  29476L107  1999-09-30   2000-01-03       0   
6       4443754   216235  031162100  1999-09-30   2000-01-03       0   
7       4443755   216235  345370100  1999-09-30   2000-01-03       0   
8       4443756   216235  812387108  1999-09-30   2000-01-03       0   
9       4443757   216235  205887102  1999-09-30   2000-01-03       0   
10      4443758   216235  369604103  1999-09-30   2000-01-03       0   
11      4443759   216235  302290101  1999-09-30   2000-01-03       0   
12      4443760   216235  693506107  1999-09-30   2000-01-03       0   
13      4443761   216235  G90076103  1999-09-30   2000-01-03       0   
14      4443762   216235  459506101  1999-09-30   2000-01-03       0   
15      4443763   216235  048825103  1999-09-30   2000-01-03       0   
16      4443764   216235  285661104  1999-09-30   2000-01-03       0   
17      4443765   216235  026874107  1999-09-30   2000-01-03       0   
18      4443766   216235  011659109  1999-09-30   2000-01-03       0   
19      4443767   216235  05564E106  1999-09-30   2000-01-03       0   
20      4443768   216235  427866108  1999-09-30   2000-01-03       0   
21      4443769   216235  494368103  1999-09-30   2000-01-03       0   
22      4443770   216235  026609107  1999-09-30   2000-01-03       0   
23      4443771   216235  143658102  1999-09-30   2000-01-03       0   
24      4443772   216235  053015103  1999-09-30   2000-01-03       0   
25      4443773   216235  156700106  1999-09-30   2000-01-03       0   
26      4443774   216235  984121103  1999-09-30   2000-01-03       0   
27      4443775   216235  362320103  1999-09-30   2000-01-03       0   
28      4443776   216235  247126105  1999-09-30   2000-01-03       0   
29      4443777   216235  370334104  1999-09-30   2000-01-03       0   
30      4443778   216235  962166104  1999-09-30   2000-01-03       0   
31      4443779   216235  607059102  1999-09-30   2000-01-03       0   
32      4443780   216235  209615103  1999-09-30   2000-01-03       0   
33      4443781   216235  423074103  1999-09-30   2000-01-03       0   
34      4443782   216235  806857108  1999-09-30   2000-01-03       0   
35      4443783   216235  928662303  1999-09-30   2000-01-03       0   
36      4443784   216235  191216100  1999-09-30   2000-01-03       0   
37      4443785   216235  313586109  1999-09-30   2000-01-03       0   
38      4443786   216235  604059105  1999-09-30   2000-01-03       0   
39      4443787   216235  025816109  1999-09-30   2000-01-03       0   
40      4443788   216235  413619107  1999-09-30   2000-01-03       0   
41      4443789   216235  149123101  1999-09-30   2000-01-03       0   
42      4443790   216235  55268B106  1999-09-30   2000-01-03       0   
43      4443791   216235  716941109  1999-09-30   2000-01-03       0   
44      4443792   216235  589331107  1999-09-30   2000-01-03       0   
45      4443793   216235  337358105  1999-09-30   2000-01-03       0   
46      4443794   216235  133131102  1999-09-30   2000-01-03       0   
47      4443795   216235  013104104  1999-09-30   2000-01-03       0   
48      4443796   216235  260543103  1999-09-30   2000-01-03       0   
49      4443797   216235  338915101  1999-09-30   2000-01-03       0   
50      4443798   216235  742718109  1999-09-30   2000-01-03       0   
51      4443799   216235  364760108  1999-09-30   2000-01-03       0   
52      4443800   216235  06423A103  1999-09-30   2000-01-03       0   
53      4443801   216235  458140100  1999-09-30   2000-01-03       0   
54      4443802   216235  635405103  1999-09-

In [27]:
Sce.tail()

iRECORD_ID     iCIK     iCUSIP iPERIOD_END iFILING_DATE  iAMEND  \
57569231    74561590  1730479  039483102  2020-03-31   2020-04-23       1   
57569232    74561591  1730479  88160R101  2020-03-31   2020-04-23       1   
57569233    74561592  1730479  921937793  2020-03-31   2020-04-23       1   
57569234    74561593  1730479  863667101  2020-03-31   2020-04-23       1   
57569235    74561594  1730479  232806109  2020-03-31   2020-04-23       1   

          iRESTATEMENT  iTYPE    iQTY  iMARKET_VALUE  iLONG_FRACTION  
57569231             0      0   300.0        11000.0        0.000086  
57569232             0      0    25.0        13000.0        0.000102  
57569233             0      0   230.0        25000.0        0.000196  
57569234             0      0  1030.0       171000.0        0.001341  
57569235             0      0   100.0         2000.0        0.000016

In [17]:
28287.0/3134550.0

0.00902426185576877

In [18]:
79199.0/5690620.0

0.013917464177892743

In [4]:
Sce.iCIK.unique()
len(Sce.iCIK.unique())
##基金数量

9540

In [5]:
len(Sce.iCUSIP.unique())
# 股票数量

131157

In [19]:
131157/9540

13.74811320754717

### iAMEND,iRESTATEMENT,iTYPE

In [ ]:
# iAMEND(修改) --- [0,1]  this variable can be used to choose suitable funds
# iRESTATEMENT(重申，再次声明) --- [0,1]
# iTYPE --- [0,1,2,3,4,5] --- what types/classifications

#### amend

In [25]:
Sce.iAMEND.describe()

count    5.756924e+07
mean     8.697329e-02
std      2.817959e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: iAMEND, dtype: float64

In [32]:
amend1 = Sce[Sce['iAMEND'] == 1]
len(amend1)

5006986

In [33]:
len(amend1)/len(Sce) 

0.08697329247169443

In [7]:
Sce.iAMEND.unique()

array([0, 1], dtype=int64)

In [6]:
len(Sce.iAMEND.unique())

2

#### Restatement

In [8]:
Sce.iRESTATEMENT.unique()

array([0, 1], dtype=int64)

In [10]:
len(Sce.iRESTATEMENT.unique())

2

In [54]:
Restatement1 = Sce[Sce['iRESTATEMENT'] == 1]
len(Restatement1)

4406208

In [55]:
len(Restatement1)/len(Sce) 

0.07653754515693069

#### type

In [62]:
type1 = Sce[['iTYPE']]

In [67]:
type2 = Sce.iTYPE

In [63]:
type(type1)

pandas.core.frame.DataFrame

In [68]:
type2.value_counts()

0    56703261
1      398090
2      289728
3      177434
4         387
5         336
Name: iTYPE, dtype: int64

In [12]:
Sce.iTYPE.unique()

array([0, 1, 3, 2, 5, 4], dtype=int64)

In [11]:
len(Sce.iTYPE.unique())

6

## 单独分析一支基金

### fund1

In [35]:
fund1 = Sce[Sce['iCIK'] == 216235]

In [36]:
fund1.shape

(775, 11)

In [43]:
fund11 = fund1.sort_values(by=['iPERIOD_END'])

In [45]:
fund11.iPERIOD_END.unique()

array(['1999-09-30', '1999-12-31', '2000-03-31', '2000-06-30',
       '2000-12-31', '2001-03-31', '2001-06-30', '2002-03-31'],
      dtype=object)

In [44]:
fund11

iRECORD_ID    iCIK     iCUSIP iPERIOD_END iFILING_DATE  iAMEND  \
0           4443748  216235  055622104  1999-09-30   2000-01-03       0   
60          4443808  216235  375766102  1999-09-30   2000-01-03       0   
59          4443807  216235  071813109  1999-09-30   2000-01-03       0   
58          4443806  216235  254687106  1999-09-30   2000-01-03       0   
57          4443805  216235  077853109  1999-09-30   2000-01-03       0   
56          4443804  216235  205363104  1999-09-30   2000-01-03       0   
55          4443803  216235  616880100  1999-09-30   2000-01-03       0   
54          4443802  216235  635405103  1999-09-30   2000-01-03       0   
53          4443801  216235  458140100  1999-09-30   2000-01-03       0   
52          4443800  216235  06423A103  1999-09-30   2000-01-03       0   
51          4443799  216235  364760108  1999-09-30   2000-01-03       0   
50          4443798  216235  742718109  1999-09-30   2000-01-03       0   
49          4443797  216235  338915101  1999-09-30   2000-01-03       0   
48          4443796  216235  260543103  1999-09-30   2000-01-03       0   
47          4443795  216235  013104104  1999-09-30   2000-01-03       0   
46          4443794  216235  133131102  1999-09-30   2000-01-03       0   
45          4443793  216235  337358105  1999-09-30   2000-01-03       0   
44          4443792  216235  589331107  1999-09-30   2000-01-03       0   
61          4443809  216235  371901109  1999-09-30   2000-01-03       0   
43          4443791  216235  716941109  1999-09-30   2000-01-03       0   
63          4443811  216235  277461109  1999-09-30   2000-01-03       0   
65          4443813  216235  339324402  1999-09-30   2000-01-03       0   
82          4443830  216235  08658U101  1999-09-30   2000-01-03       0   
81          4443829  216235  718154107  1999-09-30   2000-01-03       0   
80          4443828  216235  81760N109  1999-09-30   2000-01-03       0   
79          4443827  216235  534187109  1999-09-30   2000-01-03       0   
78          4443826  216235  291011104  1999-09-30   2000-01-03       0   
77          4443825  216235  950590109  1999-09-30   2000-01-03       0   
76          4443824  216235  025537101  1999-09-30   2000-01-03       0   
75          4443823  216235  488360108  1999-09-30   2000-01-03       0   
74          4443822  216235  166751107  1999-09-30   2000-01-03       0   
73          4443821  216235  833034101  1999-09-30   2000-01-03       0   
72          4443820  216235  17275R102  1999-09-30   2000-01-03       0   
71          4443819  216235  478160104  1999-09-30   2000-01-03       0   
70          4443818  216235  693475105  1999-09-30   2000-01-03       0   
69          4443817  216235  110122108  1999-09-30   2000-01-03       0   
68          4443816  216235  655844108  1999-09-30   2000-01-03       0   
67          4443815  216235  364730101  1999-09-30   2000-01-03       0   
66          4443814  216235  382550101  1999-09-30   2000-01-03       0   
64          4443812  216235  370442105  1999-09-30   2000-01-03       0   
42          4443790  216235  55268B106  1999-09-30   2000-01-03       0   
62          4443810  216235  585509102  1999-09-30   2000-01-03       0   
40          4443788  216235  413619107  1999-09-30   2000-01-03       0   
18          4443766  216235  011659109  1999-09-30   2000-01-03       0   
17          4443765  216235  026874107  1999-09-30   2000-01-03       0   
16          4443764  216235  285661104  1999-09-30   2000-01-03       0   
15          4443763  216235  048825103  1999-09-30   2000-01-03       0   
14          4443762  216235  459506101  1999-09-30   2000-01-03       0   
13          4443761  216235  G90076103  1999-09-30   2000-01-03       0   
12          4443760  216235  693506107  1999-09-30   2000-01-03       0   
10          4443758  216235  369604103  1999-09-30   2000-01-03       0   
19          4443767  216235  05564E106  1999-09-30   2000-01-03       0   
9           4443757  216235  20588

### fund2

In [46]:
Sce.iCIK.unique()

array([ 216235, 1044330, 1086755, ..., 1766005, 1660405, 1638520],
      dtype=int64)

In [47]:
fund2 = Sce[Sce['iCIK'] == 1044330]
fund2.shape

(11679, 11)

In [48]:
fund22 = fund2.sort_values(by=['iPERIOD_END'])

In [49]:
fund22.iPERIOD_END.unique()

array(['1999-06-30', '1999-12-31', '2000-03-31', '2000-06-30',
       '2000-09-30', '2000-12-31', '2001-03-31', '2001-12-31',
       '2002-03-31', '2002-06-30', '2002-09-30', '2002-12-31',
       '2003-03-31', '2003-06-30', '2003-09-30', '2003-12-31',
       '2004-03-31', '2004-06-30', '2004-09-30', '2004-12-31',
       '2005-03-31', '2005-06-30', '2005-09-30', '2005-12-31',
       '2006-03-31', '2006-06-30', '2006-09-30', '2006-12-31',
       '2007-03-31', '2007-06-30', '2007-09-30', '2007-12-31',
       '2008-03-31', '2008-06-30', '2008-09-30', '2008-12-31',
       '2009-03-31', '2009-06-30', '2009-09-30', '2009-12-31',
       '2010-03-31', '2010-06-30', '2010-09-30', '2010-12-31',
       '2011-03-31', '2011-06-30', '2011-09-30', '2011-12-31',
       '2012-03-31', '2012-06-30', '2012-09-30', '2012-12-31',
       '2013-03-31', '2013-06-30', '2013-09-30', '2013-12-31',
       '2014-03-31', '2014-06-30', '2014-09-30', '2014-12-31',
       '2015-03-31', '2015-06-30', '2015-09-30', '2015-

### fund3

In [50]:
fund3 = Sce[Sce['iCIK'] == 1086755]
fund3.shape

(1386, 11)

In [51]:
fund33 = fund3.sort_values(by=['iPERIOD_END'])

In [52]:
fund33.iPERIOD_END.unique()

array(['1999-12-31', '2000-03-31', '2000-09-30', '2001-06-30',
       '2001-12-31', '2002-03-31', '2002-06-30', '2002-09-30',
       '2003-03-31', '2003-06-30', '2003-09-30', '2005-06-30',
       '2005-09-30', '2005-12-31', '2006-03-31', '2006-06-30'],
      dtype=object)

## old 

In [ ]:
216235

In [8]:
SEC13F.head()
# iCIK 基金编号
# iCUSIP 基金中股票代码
# iPERIOD_END 期间开始的时间？？？ why there is "end"
# iFILING_DATE 交报告的时间？？？
# iAMEND 
# iRESTATEMENT
# iTYPE
# iQTY - Int number of shares 
# iMARKET_VALUE - Float total amount of money invested 
# iLONG_FRACTION - long的stock占总股数的比例

iRECORD_ID    iCIK     iCUSIP iPERIOD_END iFILING_DATE  iAMEND  \
0     4443748  216235  055622104  1999-09-30   2000-01-03       0   
1     4443749  216235  020039103  1999-09-30   2000-01-03       0   
2     4443750  216235  713448108  1999-09-30   2000-01-03       0   
3     4443751  216235  002824100  1999-09-30   2000-01-03       0   
4     4443752  216235  05964H105  1999-09-30   2000-01-03       0   

   iRESTATEMENT  iTYPE      iQTY  iMARKET_VALUE  iLONG_FRACTION  
0             0      0   28287.0      3134550.0        0.009282  
1             0      0   79199.0      5690620.0        0.016851  
2             0      0  186140.0      5795950.0        0.017163  
3             0      0  169555.0      6290420.0        0.018627  
4             0      0   16897.0       174250.0        0.000516

In [9]:
SEC13F.tail()

iRECORD_ID     iCIK     iCUSIP iPERIOD_END iFILING_DATE  iAMEND  \
57569231    74561590  1730479  039483102  2020-03-31   2020-04-23       0   
57569232    74561591  1730479  88160R101  2020-03-31   2020-04-23       0   
57569233    74561592  1730479  921937793  2020-03-31   2020-04-23       0   
57569234    74561593  1730479  863667101  2020-03-31   2020-04-23       0   
57569235    74561594  1730479  232806109  2020-03-31   2020-04-23       0   

          iRESTATEMENT  iTYPE    iQTY  iMARKET_VALUE  iLONG_FRACTION  
57569231             0      0   300.0        11000.0        0.000086  
57569232             0      0    25.0        13000.0        0.000102  
57569233             0      0   230.0        25000.0        0.000196  
57569234             0      0  1030.0       171000.0        0.001341  
57569235             0      0   100.0         2000.0        0.000016